/**/auv_yolo_detector:
  paths:
    yolo_model: '/config/best_real_2.pt'
    bags: "/home/fm/KTH_Courses/ResearchProject/RProj_GitRepoFork/colcon_ws/src/smarc2/perception/alars/auv_yolo_detector/bags/djuro_2025_nov"
  rosbag:
    duration: 20.0 # [s]
    frame_period: 2.0 # [s] approximated time between frames
    initial_frame_index: 114 # change to a non-zero if u already have frames within directory
